language: ruby

before_install:
 - phpenv global 7.0

install:
 - php install html5validator

script:
 - bundle exec rake test
 - html5validator --root _site/
  
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
    - openjdk-8-jre

dist: xenial
os: linux
