set windows-shell := ["powershell.exe", "-c"]

default: install build test

install:
    bundle install

build *ARGS:
    bundle exec jekyll build {{ARGS}}
    test -f _site/static/model/embeddings-all-MiniLM-L6-v2.json
    test -f _site/static/model/embeddings-bge-small-en-v1.5.json

test:
    bundle exec rake checkhtml
    export LANG=en_US.UTF-8 && export LANGUAGE=en_US:en && export LC_ALL=en_US.UTF-8 && bundle exec rake spellcheck

eval:
    python3 tests/eval_retrieval.py

run:
    bundle exec jekyll serve

