name: Test ficksworkshop.com Repository
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.3 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: sudo apt-get update -y && sudo apt-get -y install aspell aspell-en python3-pip locales openjdk-8-jre
    - run: echo "en_US UTF-8" | sudo tee -a /etc/locale.gen
    - run: locale-gen en_US.UTF-8
    - run: pip install html5validator
    - run: export LANG=en_US.UTF-8 && export LANGUAGE=en_US:en && export LC_ALL=en_US.UTF-8 && bundle exec rake test
    - run: html5validator --root _site/
    # - run: bash ./spellcheck.sh